[metadata]
name = vaultstack-dashboard
version = 1.0.0
summary = VaultStack - OpenStack Backup & Restore Dashboard Plugin
author = VaultStack Team

[options]
packages = find:
include_package_data = True
install_requires =
    django>=4.2
    requests>=2.31.0

[options.package_data]
* = *.html, *.css, *.js, *.png, *.gif, *.ico, *.py

[options.entry_points]
openstack_dashboard.enabled =
    _91_vaultstack_project_group   = vaultstack_dashboard.enabled._91_vaultstack_project_group
    _92_vaultstack_project_backup  = vaultstack_dashboard.enabled._92_vaultstack_project_backup
    _93_vaultstack_admin_group     = vaultstack_dashboard.enabled._93_vaultstack_admin_group
    _94_vaultstack_admin_panel     = vaultstack_dashboard.enabled._94_vaultstack_admin_panel
